configfile: "config.yaml"

rule all:	
	input: 
	    config["Bash_file"]


rule coverage:
	input:
	    config["Table_coverage"],
	    config["Path_save_result"]
	params:
	    config["N_threds_cov"]
	output:
	    config["Table_python"]
	script:
	    config["Path_script_cov"]


rule Fp_Fg_computation:
	input:
	    config["Table_python"]
	params:
	    config["TC_fin"],
	    config["Cov_fin"]
	output:
            config["Table_out"]
	script:
            config["Path_script_py"]


rule Bash_file_generator:
	input:
	    config["Table_out"],
	    config["Path_synthetic_dilutions"]
	params:
	    config["TC_fin"],
	    config["N_threds_samtools"]
	output:
	    config["Path_bash_file"]
	script: 
	    config["Path_script_samtools"]

rule bash_execution:
	input:
	    config["Bash_file"]
	shell:
	    "bash {input}"
